# This file contains the configuration for the results analysis that will be performed on the SUMO simulation results.
# configurations/analysis_config.yaml

analysis_settings:
  analyze_queue: true
  analyze_summary: true
  analyze_turn_counts: false
  analyze_emission: true

  analyze_stop_infos: false
  analyze_speed: false
  edge_traffic_measures: false
  analyze_vehicle_routes: false
  analyze_fcd: false
  analyze_delay: false
  analyze_route: false
  analyze_tripinfo: false

