# This file contains the configuration for the datasets that will be fetched from the City of Toronto's Open Data Portal.
# configurations/datasets_config.yaml


# City of Toronto transportation datasets to fetch
transportation_datasets:

  # 1. Traffic volumes at intersections for all modes
  traffic-volumes-at-intersections-for-all-modes:
    fetch_data: true
    target_files:
      tmc_raw_data_2020_2029:
        format: csv
      tmc_data_dictionary:
        format: csv
      tmc_summary_data:
        format: csv
      tmc_data_dictionary:
        format: xlsx

  # 2. Traffic volumes midblock vehicle speed, volume, and classification counts
  traffic-volumes-midblock-vehicle-speed-volume-and-classification-counts:
    fetch_data: true
    target_files:
      svc_raw_data_volume_2020_2024:
        format: csv
      svc_raw_data_volume_2015_2019:
        format: csv
      fwha_classification:
        format: csv
      svc_data_dictionary:
        format: csv
      svc_most_recent_summary_data:
        format: csv
      svc_summary_data:
        format: csv

  city-wards:
    fetch_data: true
    target_files:
      4326:
        format: geojson

  neighbourhoods:
    fetch_data: true
    target_files:
      4326:
        format: geojson # options "4326 geojson", "shp", "csv"

  traffic-signal-timing:
    fetch_data: true
    target_files:
      timing:
        format: csv
      timing:
        format: zip

  toronto-centreline-tcl:
    fetch_data: true
    target_files:
      4326:
        format: geojson

  traffic-signals-tabular:
    fetch_data: true
    target_files:
      4326:
        format: csv
      readme:
        format: xlsx

  road-restrictions:
    fetch_data: false
    target_files:
      restrictions:
        format: csv
      readme:
        format: xlsx

  turn-restrictions:
    fetch_data: false
    target_files:
      restrictions:
        format: zip
      restrictions:
        format: shp

  cycling-network:
    fetch_data: true
    target_files:
      4326:
        format: geojson

  ttc-routes-and-schedules:
    fetch_data: false
    target_files:
      ttc:
        format: zip

  bikeways:
    fetch_data: true
    target_files:
      4326:
        format: geojson

  pedestrian-network:
    fetch_data: true
    target_files:
      4326:
        format: geojson
      readme:
        format: xlsx
      analysis:
        format: pdf

  vehicles-utilizing-green-technology:
    fetch_data: false
    target_files:
      green:
        format: xlsx


# Old version of traffic volumes dataset
# # City of Toronto transportation datasets to fetch
# transportation_datasets:
#   traffic-volumes-at-intersections-for-all-modes:
#     fetch_data: true
#     target_files:
#       raw-data-2020-2029:
#         format: csv
#       locations:
#         format: csv
#       count_metadata:
#         format: csv