# This file contains the configuration for the lanes that will be included in the building of the network.
# configurations/lanes_config.yaml

# Network lanes to include
lanes:

  # Arterial exclude the secondary and local roads in the network
  arterial:
    - "Expressway"
    - "Major Arterial"
    - "Minor Arterial"
    - "Expressway Ramp"
    - "Major Arterial Ramp"
    - "Minor Arterial Ramp"
    - "Busway"
    - "Collector"
    - "Collector Ramp"
    - "Access Road"

  # Collector exclude the local roads in the network
  collector:
    - "Expressway"
    - "Major Arterial"
    - "Minor Arterial"
    - "Expressway Ramp"
    - "Major Arterial Ramp"
    - "Minor Arterial Ramp"
    - "Busway"
    - "Collector"
    - "Collector Ramp"
    - "Access Road"

  # Local include all the roads in the network
  local:
    - "Expressway"
    - "Major Arterial"
    - "Minor Arterial"
    - "Expressway Ramp"
    - "Major Arterial Ramp"
    - "Minor Arterial Ramp"
    - "Busway"
    - "Collector"
    - "Collector Ramp"
    - "Access Road"
    - "Local"
    - "Laneway"
    - "Walkway"
    - "Trail"
    - "Other Ramp"




