# Main configuration file for the Toronto Traffic Simulation project.
core:
  project_name: "Toronto Traffic Simulation"
  version: "2.0.0"
  
# Specify which execution profile to use.
active_execution_profile: settings_1

# List of configuration files to import.
includes:
  - execution_config.yaml
  - network_config.yaml
  - detectors_config.yaml
  - datasets_config.yaml
  - lanes_config.yaml
  - routing_config.yaml
  - simulation_config.yaml
  - paths_config.yaml
  - traffic_config.yaml
  - analysis_config.yaml

# Logging configuration.
logging:
  enable_console: true
  enable_file: true
  log_dir: "logs"
  log_level: "INFO" # "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
