# This file contains the main configuration for the simulation.
# configurations/main.yaml

# Main configuration file
imports:
  - execution_config.yaml
  - network_config.yaml
  - detectors_config.yaml
  - datasets_config.yaml
  - lanes_config.yaml
  - routing_config.yaml
  - simulation_config.yaml
  - paths_config.yaml
  - traffic_config.yaml
  - analysis_config.yaml

core:
  project_name: "Toronto Traffic Simulation"
  version: "1.0.0"

# Main execution settings

execution_settings: "settings_4"

# Logging configurations
logging:
  save_logs: true
  console_output: true
  log_dir: "logs"
  log_level: "INFO" # "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"




