# Network configuration for building the SUMO network.

network:
  # Determines the geographical scope for the network.
  extent: "by_ward_name"  # Options: city_wide, by_ward_name, by_neighbourhood, by_junctions
  type: "arterial"        # Options: arterial, collector, local, junctions

  # Specific area definitions for each mode.
  area:
    city_wide: "City of Toronto"
    by_ward_name: "Scarborough-Agincourt"
    by_neighbourhood: "Woburn North"
    by_junctions:
      name: "selected_junctions"
      junction_ids: [13447816, 13447843, 13447955, 13448023, 13448086, 13448106,
                     13448133, 13448199, 13448245, 13448326, 13974857, 14070158, 20054776]
