# configurations/network.yaml
# This file contains the configuration for the network that will be built for the simulation.

network_settings:
  city_wide:
    network_area: "City of Toronto"
    network_type: "arterial" # "arterial", "collector", "local"

  by_ward_name:
    network_area: "Scarborough North" # options "Scarborough North", "Don Valley West", "Etobicoke North", "North York", "Toronto Centre"
    network_type: "arterial" # "arterial", "collector", "local"

  by_neighbourhood:
    network_area: "Old East York" # options "Lawrence Park South" "Mount Pleasant East" "North Toronto" "Casa Loma" "Danforth East York" "South Eglinton-Davisville" "Dovercourt Village" 'Junction-Wallace Emerson' 'Yonge-Bay Corridor' 'Bay-Cloverhill'
    network_type: "arterial" # "arterial", "collector", "local"






