# configurations/paths_config.yaml
# This file contains the configuration for the paths that will be used in the simulation.

# Path configurations
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  network_data: "data/sumo_networks"
  traffic_data: "data/processed/traffic_data"
  simulation_data: "data/simulation_output"
  traffic_volume_dir: "data/raw/traffic-volumes-at-intersections-for-all-modes"
  ward_boundaries_file: "data/raw/city-wards/City Wards Data - 4326.geojson"
  neighbourhood_boundaries_file: "data/raw/neighbourhoods/Neighbourhoods.geojson"