# Paths configuration for data and tools.
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  network_data: "data/sumo_networks"
  traffic_data: "data/processed/traffic_data"
  simulation_data: "data/simulation_output"
  traffic_volume_dir: "data/raw/traffic-volumes-at-intersections-for-all-modes"
  gtfs: "data/raw/gtfs"
  ward_boundaries: "data/raw/city-wards/City Wards Data - 4326.geojson"
  neighbourhood_boundaries: "data/raw/neighbourhoods/Neighbourhoods.geojson"
  sumo_tools: "${SUMO_HOME}/tools"
  centreline_geojson: "data/raw/toronto-centreline-tcl/Centreline_-_Version_2_-_4326.geojson"  # update this path as needed
